# Generated by Django 3.0.5 on 2020-04-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200429_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.TextField(blank=True, default='', max_length=25, null=True),
        ),
    ]
