# Generated by Django 3.0.5 on 2020-04-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200429_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, upload_to='<django.db.models.fields.related.OneToOneField>icons/'),
        ),
    ]
