# Generated by Django 3.0.5 on 2020-04-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_userprofile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, upload_to='<django.db.models.fields.related.OneToOneField>/icons/'),
        ),
    ]
