# Generated by Django 3.0.5 on 2020-04-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200430_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/'),
        ),
    ]
