# Generated by Django 3.0.5 on 2020-04-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20200430_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, default='', null=True, upload_to='icons/'),
        ),
    ]
