# Generated by Django 3.0.5 on 2020-04-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20200430_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, default='icons/default.jpg', null=True, upload_to='icons/'),
        ),
    ]
