# Generated by Django 3.0.4 on 2020-04-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20200430_1211'),
        ('profiles', '0015_auto_20200430_1203'),
    ]

    operations = [
    ]
