# Generated by Django 3.0.4 on 2020-04-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_merge_20200430_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, default='icons/default.jpg', null=True, upload_to='icons/'),
        ),
    ]
