# Generated by Django 3.0.5 on 2020-04-10 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0005_auto_20200410_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 12, 14, 33, 908908, tzinfo=utc)),
        ),
    ]
