# Generated by Django 3.0.5 on 2020-04-12 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0006_auto_20200410_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 7, 49, 44, 700830, tzinfo=utc)),
        ),
    ]
