# Generated by Django 3.0.5 on 2020-04-16 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0007_auto_20200412_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 6, 36, 28, 453622, tzinfo=utc)),
        ),
    ]
