# Generated by Django 3.0.4 on 2020-04-29 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0020_auto_20200429_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 12, 20, 17, 501726, tzinfo=utc)),
        ),
    ]
