# Generated by Django 3.0.5 on 2020-04-30 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0021_auto_20200429_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 7, 27, 22, 968072, tzinfo=utc)),
        ),
    ]
