# Generated by Django 3.0.4 on 2020-04-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0021_auto_20200429_1520'),
        ('postfeed', '0028_auto_20200430_1136'),
    ]

    operations = [
    ]
