# Generated by Django 3.0.5 on 2020-04-30 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0029_auto_20200430_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 9, 11, 0, 131848, tzinfo=utc)),
        ),
    ]
