# Generated by Django 3.0.4 on 2020-04-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0030_auto_20200430_1211'),
        ('postfeed', '0029_auto_20200430_1203'),
        ('postfeed', '0029_merge_20200430_1202'),
    ]

    operations = [
    ]
