# Generated by Django 3.0.4 on 2020-04-30 10:47

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postfeed', '0031_merge_20200430_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='users_reaction',
            field=models.ManyToManyField(blank=True, related_name='react', to=settings.AUTH_USER_MODEL, verbose_name='user_reaction'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 10, 47, 12, 506082, tzinfo=utc)),
        ),
    ]
