# Generated by Django 3.0.5 on 2020-05-04 08:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0033_auto_20200430_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 8, 0, 44, 96492, tzinfo=utc)),
        ),
    ]
