# Generated by Django 3.0.4 on 2020-05-08 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0034_auto_20200504_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 19, 42, 5, 377100, tzinfo=utc)),
        ),
    ]
