# Generated by Django 3.0.5 on 2020-05-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0034_auto_20200504_1100'),
        ('postfeed', '0036_auto_20200509_1632'),
    ]

    operations = [
    ]
